version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./mysql/insert.sql:/docker-entrypoint-initdb.d/insert.sql:ro
    networks:
      - app-network

  backend:
    image: akshunsinha/itransition:backend
    container_name: backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "${BACKEND_PORT}:3100"
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    image: akshunsinha/itransition:frontend
    container_name: frontend
    restart: unless-stopped
    # entrypoint: ["bash"]
    # tty: true
    environment:
      REACT_APP_API_BASE_URL: http://localhost:${BACKEND_PORT}/api
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
